Gemfile
Gemfile.lock
spec/rails_helper.rb

Hi all. I have added simplecov in the Gemfile and in Rails Helper. This should work but we won't know until we write the first test. I will check then to make sure it's working correctly.
Please merge to master. Thanks.

Added SimpleCov

---

README.md

-
-
-
-
-
* Tested on RSPEC?
* All test passing?

formatting picture in readme

---

.gitignore
db/csv/station.csv
db/seeds.rb

- Seeds the stations into the database
- Adds the station.csv file to the repo
N/A
* Tested on RSPEC? Yes
* All test passing? Yes
* Ran on Local Host? Yes

Stations seed

---

Gemfile
Gemfile.lock
app/assets/stylesheets/application.scss
app/views/stations/index.html.erb
app/views/stations/show.html.erb
app/views/trips/index.html.erb
app/views/trips/show.html.erb
spec/features/admin/station/admin_can_delete_station_spec.rb
spec/features/admin/station/admin_can_edit_station_spec.rb
spec/features/admin/station/admin_can_see_stations_index_spec.rb
spec/features/admin/station/admin_sees_station_show_spec.rb
spec/features/admin/trips/admin_can_delete_trip_spec.rb
spec/features/admin/trips/admin_can_edit_trip_spec.rb
spec/features/admin/trips/admin_visit_show_spec.rb
spec/features/admin/trips/admin_visit_trip_index_spec.rb

- Added font awesome icons for edit/delete. Gemfile updated.
- Refactored tests to allow for use of icons
-
- Removed duplicate and unnecessary testing.
-

Admin edit delete buttons

---

app/controllers/admin/dashboard_controller.rb
app/controllers/sessions_controller.rb
app/views/admin/dashboard/index.html.erb
app/views/layouts/application.html.erb
app/views/partials/_nav.html.erb
config/routes.rb
spec/features/admin/admin_visits_admin_dashboard_spec.rb
spec/features/users/user_can_logout_spec.rb
spec/features/users/user_login_spec.rb

- Admin can login and land on '/admin/dashboard'
- 
- Move flash message to nav
- 
-

Admin dashboard

---

app/controllers/cart_controller.rb
app/models/cart.rb
app/views/accessories/_accessory.html.erb
app/views/cart/index.html.erb
config/routes.rb
spec/features/visitors/accessories/visitor_can_see_accessory_show_spec.rb
spec/features/visitors/accessories/visitor_can_see_bike-shop_accessories_spec.rb
spec/features/visitors/cart/visitor_can_decrease_quantity_of_item_spec.rb
spec/features/visitors/cart/visitor_can_increase_accessory_quantity_spec.rb
spec/features/visitors/cart/visitor_can_see_all_items_after_creating_account_spec.rb
spec/features/visitors/cart/visitor_can_see_cart_index_spec.rb

- Created passing tests for increase item quantity in cart
- Created passing tests for decrease item quantity in cart
- Added scope to accessories index tests
- Created passing tests for remove accessory from cart
-
-
* Tested on RSPEC? ✔️
* Ran on Local Host? No

Completed increase, decrease quantity stories

---

app/assets/stylesheets/custom.scss
app/assets/stylesheets/helpers/_nav.scss
app/views/accessories/_accessory.html.erb
app/views/accessories/index.html.erb
app/views/accessories/show.html.erb
app/views/admin/accessories/index.html.erb
app/views/admin/dashboard/index.html.erb
app/views/partials/_nav.html.erb
spec/features/admin/dashboard/admin_visits_admin_dashboard_spec.rb

- Card structure for accessories
- add more links in nav bar 
-
- fix active/retire options 
-

Cleanup styling

---

app/views/cart/index.html.erb

- Moved subtotals for accessories in the cart to the respective accessories
-
-
-
-
* Tested on RSPEC? ✔️

Fixed subtotal styling for bike shop.

---

app/assets/stylesheets/custom.scss
app/models/station.rb
app/views/accessories/_accessory.html.erb
app/views/admin/accessories/_form.html.erb
app/views/admin/accessories/edit.html.erb
app/views/admin/accessories/index.html.erb
app/views/conditions/show.html.erb
app/views/partials/_nav.html.erb
app/views/stations/show.html.erb
app/views/trips/index.html.erb
app/views/trips/show.html.erb
spec/features/admin/dashboard/admin_can_edit_accessory_spec.rb

- Styling cleanup
- add dependency destroy to stations for trips
-
- 
-
* Tested on RSPEC?
* All test passing?

dependency

---

app/controllers/stations_controller.rb

- 
-
-
-Fixed admin update station for slug issue
-

fixed station slug update

---

app/controllers/users_controller.rb
app/views/conditions/index.html.erb
app/views/conditions/show.html.erb
app/views/stations/index.html.erb
app/views/stations/show.html.erb
app/views/trips/index.html.erb
app/views/users/_form.html.erb
app/views/users/dashboard.html.erb
app/views/users/edit.html.erb
config/routes.rb
spec/factories/users.rb
spec/features/admin/conditions/admin_can_create_new_condition_spec.rb
spec/features/admin/station/admin_creates_new_station_spec.rb
spec/features/admin/trips/admin_can_create_new_trip_spec.rb
spec/features/users/user_can_edit_info_spec.rb
spec/features/users/visitor_can_create_account_spec.rb

- Added create new to index page for conditions, trips, and stations. Also added 'Weather Conditions' to index and show for conditions.
- Added user edit functionality.
- All testing complete.
-
-

Repo links

---

app/controllers/conditions_controller.rb
app/models/condition.rb
app/models/trip.rb
app/views/conditions/dashboard.html.erb
app/views/users/dashboard.html.erb
config/routes.rb
db/migrate/20180414194526_add_condition_to_trips.rb
db/migrate/20180415002513_add_zipcode_to_conditions.rb
db/schema.rb
db/seeds.rb
spec/factories/conditions.rb
spec/factories/trips.rb
spec/features/admin/trips/admin_can_delete_trip_spec.rb
spec/features/admin/trips/admin_can_edit_trip_spec.rb
spec/features/admin/trips/admin_visit_show_spec.rb
spec/features/admin/trips/admin_visit_trip_index_spec.rb
spec/features/users/user_sees_condition_dashboard_spec.rb
spec/features/visitors/trips/visitor_can_see_trips_index_spec.rb
spec/features/visitors/trips/visitor_cannot_see_trip_edit_or_delete_link_spec.rb
spec/features/visitors/trips/visitor_sees_all_attributes_on_trip_show_page_spec.rb
spec/models/condition_spec.rb
spec/models/trip_spec.rb

- The conditions dashboard is up and running! 🙌
- This required a new migration and seeding for the new relationship (a trip belongs to a condition)
- I also added accessories seeding
-  Future fix: I think the condition model could def be refactored. It's very repetitive currently. 
- Another future fix: currently I'm hardcoding the ranges to display on the dashboard based on my knowledge of the data. Ideally this would be a method to determine which ranges to display. 
* All test passing ✔️
* Ran on Local Host ✔️

Conditions dashboard

---

app/controllers/stations_controller.rb
app/models/station.rb
app/views/stations/dashboard.html.erb
config/routes.rb
spec/features/users/user_can_see_stations_dashboard_spec.rb
spec/models/station_spec.rb

Closes #91
- Implements station dashboard and related tests
- N/A
* All test passing? ✅

Stations dashboard

---

app/controllers/admin/orders_controller.rb
app/models/order.rb
app/models/order_accessory.rb
app/models/user.rb
app/views/admin/orders/show.html.erb
db/migrate/20180415210304_add_total_to_orders.rb
db/migrate/20180415212256_add_columns_to_user.rb
db/schema.rb
spec/factories/order.rb
spec/factories/users.rb
spec/features/admin/orders/admin_can_see_order_show_page_spec.rb
spec/features/dashboards/user_or_admin_visits_trip_dashboard_spec.rb
spec/models/order_accessory_spec.rb
spec/models/trip_spec.rb

- Created passing feature and model tests for Admin can visit individual order page user story
- Created and ran migration to add first name, last name and address to the users table
- Fixed issues with the tests not returning the correct dates (due to the UTC and local time conflict)
-
-
* Tested on RSPEC?  ☑️
* All test passing?  ☑️

Admin order show page

---

db/migrate/20180416022846_add_total_to_order.rb
db/schema.rb

- Created and ran migration to add total column to the orders table
-
-
-
-
* Tested on RSPEC? Yes
* All test passing? Yes

Created migration for the orders table.

---

app/controllers/admin/accessories_controller.rb
app/models/accessory.rb
app/views/admin/accessories/_form.html.erb
spec/features/admin/accessories/admin_can_add_accessory_spec.rb

- Added tests for the uniqueness of title, the presence of title, the positive value for price, and default image.
-
-
-
-

New accessory

---

app/models/trip.rb

-STRFTIME date for methods needing to access condition by date.
-
-
- Fixed trips-dashboard, broke tests though.
-
* Tested on RSPEC? Y - ALL BROKEN! Ha.
* All test passing? N
* Ran on Local Host? Y Working though!

STRFTIME date for methods needing to access condition by date.

---

app/controllers/admin/accessories_controller.rb
app/views/admin/accessories/_form.html.erb

- Paperclip fix for uploading image.
-
-
-
-
* Tested on RSPEC?
* All test passing?

Fix for image upload.

---

app/models/trip.rb
spec/factories/conditions.rb
spec/features/dashboards/user_or_admin_visits_trip_dashboard_spec.rb
spec/models/trip_spec.rb

- Changing broken tests in the trip_spec and trip_features specs
-
-
-
-
* Tested on RSPEC? Yes
* All test passing? Yes

Fixing broken trips dasbhoard tests.

---

app/controllers/admin/base_controller.rb
app/controllers/orders_controller.rb
app/controllers/users_controller.rb
config/routes.rb
spec/features/users/user_can_see_orders_spec.rb
spec/features/users/user_can_submit_order_spec.rb
spec/features/visitors/visitor_cannot_see_restricted_pages_spec.rb

- Made sure user can't see admin pages
- Made sure user can't edit another users data
- Made user that orders can only be accessed by the right users
- Made sure that users cannot access/edit another users information
- N/A
* All test passing?  ✅

User cannot see restricted pages

---

app/controllers/admin/accessories_controller.rb
app/controllers/admin/conditions_controller.rb
app/controllers/admin/stations_controller.rb
app/controllers/admin/trips_controller.rb
app/controllers/cart_controller.rb
spec/features/admin/accessories/admin_can_add_accessory_spec.rb
spec/features/admin/conditions/admin_can_create_new_condition_spec.rb
spec/features/admin/conditions/admin_can_delete_condition_spec.rb
spec/features/admin/conditions/admin_can_edit_condition_spec.rb
spec/features/admin/station/admin_can_delete_station_spec.rb
spec/features/admin/trips/admin_can_delete_trip_spec.rb
spec/features/visitors/cart/visitor_can_remove_accessory_from_cart_spec.rb

- Flash refactors - cart link
-
-
-
-

Flash refactors

---

app/controllers/application_controller.rb
app/models/station.rb
app/views/stations/show.html.erb
spec/features/admin/station/admin_can_edit_station_spec.rb
spec/features/users/user_can_see_extra_station_info_spec.rb
spec/features/visitors/stations/visitor_cant_see_extra_data_spec.rb
spec/models/station_spec.rb

Closes #92 #132 
- Adds extra data about stations for logged in users
- N/A
* All test passing? ✅

Stations show extra info for users/admins

---

app/assets/stylesheets/custom.scss
app/assets/stylesheets/helpers/_nav.scss
app/views/partials/_nav.html.erb

- formatting nav bar so flash messages fit 
-
-
-
-

Margaret refactor

---

app/assets/stylesheets/custom.scss
app/controllers/admin/stations_controller.rb
app/views/admin/accessories/index.html.erb
app/views/orders/show.html.erb
spec/features/users/user_can_submit_order_spec.rb

Closes #140 
Closes #142 
Closes #121 
- Reformats the order show page
- Fixes the slug issue on the station edit for admins
- Fixes the issue where the Retire/Reactivate links on admin item index would not work
* All test passing? ✅

Order pages fixes and slug issue

---

app/models/condition.rb
app/views/admin/accessories/index.html.erb
app/views/admin/dashboard/index.html.erb
app/views/admin/orders/show.html.erb
app/views/admin/stations/_form.html.erb
app/views/admin/trips/_form.html.erb
app/views/orders/show.html.erb
app/views/stations/show.html.erb
spec/features/admin/orders/admin_can_see_order_show_page_spec.rb
spec/features/users/user_can_submit_order_spec.rb

- Changes styling of various pages 
- Fixes conditions so they can be destroyed
* All test passing? ✅

Styling fixes and conditions fix

---

app/views/admin/orders/show.html.erb
app/views/orders/show.html.erb
spec/features/users/user_can_submit_order_spec.rb

- Added time to order date. Formatted
-
-
- Tests
-

Wildcard tyler
